name: nson
description: NSON (Network Serialization Object Notation) - A lightweight binary serialization format with automatic Dart object conversion and JSON interoperability.
version: 1.1.1
# repository: https://github.com/danclive/nson-dart

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
